### ISSUE TITLE
CI: Auto-build and push docker image upon version tagging

### ISSUE THREAD

**Issue by dcwangmit01** [parinithshekar/gitsink#2]
An example can be found here:
https://github.com/cisco-sso/kdk

Use CircleCI instead of Travis.

**Comment by parinithshekar** [comment]
I think I've covered this [here](https://github.com/parinithshekar/gitsink/blob/6a78469ed03ac333566b694e75ed81cf7f20bb03/.circleci/config.yml#L53). I'll modify it a bit according to the kdk repo
